Added test of options
Added script test_option which:
- compile and run without option
- compile with option given as argument, run
- diff on the two outputs, fails if different outputs

config file checks for existence of compiler (fails if not exist)

statics1.ept is a copy of statics.ept ; statics2.ept depends on statics1.ept
instead of statics.ept (so as dependency order => lexical order on file names)

diff --git a/test/scripts/config b/test/scripts/config
--- a/test/scripts/config
+++ b/test/scripts/config
@@ -10,7 +10,13 @@ if [ -x $COMPILER_DIR/heptc.native ];
 then
     COMPILER=heptc.native
 else
-    COMPILER=heptc.byte
+    if [ -x $COMPILER_DIR/heptc.byte ];
+    then    
+        COMPILER=heptc.byte
+    else
+        echo "Error: no compiler found."
+        exit 2
+    fi
 fi
 
 HEPTC="../$COMPILER_DIR/$COMPILER -stdlib ../../lib"
